name: "two_model"
backend: "python"
max_batch_size: 0

input [
    {
        name: "two_input"
        data_type: TYPE_FP32
        dims: [ -1 ]
    }
]

output [
    {
        name: "two_output"
        data_type: TYPE_FP32
        dims: [ -1 ]
    }
]

instance_group [
    {
        count: 1
        kind: KIND_CPU
    }
]